version: "3"

services:
   rates:
     build: .
     env_file:
       - .env
     links:
       - postgres
       - redis
     ports:
       - 8888:8888
     volumes:
       - .:/rates/
     networks:
       - rates

   postgres:
     image: postgres:14.5
     ports:
       - "15432:5432"
     env_file:
       - .env
     restart: always
     networks:
       - rates

   redis:
     image: redis:7.2.1-alpine
     env_file:
       - .env
     ports:
       - 6379
     restart: always
     networks:
       - rates

networks:
  rates:
    external:
      name: rates-net