version: "3"

services:
   rates:
     build: .
     command: bash -c "
         python manage.py migrate
         && python manage.py generate_periodic_tasks
         && python manage.py runserver 0.0.0.0:8888
       "
     env_file:
       - .env
     links:
       - postgres
       - redis
     ports:
       - 8888:8888
     volumes:
       - .:/app/
     networks:
       - rates

   postgres:
     image: postgres:14.5
     ports:
       - "15432:5432"
     env_file:
       - .env
     networks:
       - rates

   redis:
     image: redis:7.2.1-alpine
     env_file:
       - .env
     ports:
       - 6379
     networks:
       - rates

   celery: &celery_template
     build: .
     command: bash -c "celery -A rates worker --loglevel=info"
     env_file:
       - .env
     depends_on:
      - redis
      - postgres
      - rates
     links:
      - redis
      - rates
     networks:
       - rates
     volumes:
       - .:/app/

   beat:
     <<: *celery_template
     command: bash -c "celery -A rates beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"

networks:
  rates:
    external:
      name: rates-net