name: rates-backend CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    services:
      postgres:
        image: postgres:14.5
        ports:
          - "15432:5432"
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
    env:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASS: ""
      DJANGO_SETTINGS_MODULE: rates.settings
      CACHE_TIMEOUT: 900
      HOUR_TO_RUN_PERIODIC_TASK: 9
      MINUTE_TO_RUN_PERIODIC_TASK: 50

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        pip install --no-cache-dir --upgrade pip
        pip install --no-cache-dir poetry==1.7.1
        poetry config virtualenvs.create false
        poetry install
    - name: check codestyle
      run: |
        isort . --check
        flake8 .
        black . --check
    - name: run tests
      run: |
        pytest
        
